-- ============================================================
-- V1: Core Schema
-- ============================================================

-- Users
CREATE TABLE users (
    id          BIGSERIAL PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    full_name   VARCHAR(255) NOT NULL,
    role        VARCHAR(50)  NOT NULL DEFAULT 'ROLE_USER',
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Refresh tokens (for JWT rotation)
CREATE TABLE refresh_tokens (
    id          BIGSERIAL PRIMARY KEY,
    token       VARCHAR(512) NOT NULL UNIQUE,
    user_id     BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at  TIMESTAMP    NOT NULL,
    revoked     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- Accounts (checking, savings, credit, etc.)
CREATE TABLE accounts (
    id           BIGSERIAL PRIMARY KEY,
    user_id      BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    name         VARCHAR(255)    NOT NULL,
    account_type VARCHAR(50)     NOT NULL,   -- CHECKING, SAVINGS, CREDIT, INVESTMENT
    balance      NUMERIC(19, 4)  NOT NULL DEFAULT 0,
    currency     VARCHAR(10)     NOT NULL DEFAULT 'USD',
    created_at   TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Categories (seeded defaults + user-defined)
CREATE TABLE categories (
    id          BIGSERIAL PRIMARY KEY,
    user_id     BIGINT       REFERENCES users(id) ON DELETE CASCADE,  -- NULL = global default
    name        VARCHAR(100) NOT NULL,
    icon        VARCHAR(50),
    color       VARCHAR(20),
    is_default  BOOLEAN      NOT NULL DEFAULT FALSE
);

-- Seed default categories (user_id = NULL means available to all)
INSERT INTO categories (name, icon, color, is_default) VALUES
    ('Food & Dining',     'utensils',      '#FF6B6B', TRUE),
    ('Transportation',    'car',           '#4ECDC4', TRUE),
    ('Housing & Rent',    'home',          '#45B7D1', TRUE),
    ('Utilities',         'zap',           '#96CEB4', TRUE),
    ('Entertainment',     'film',          '#FFEAA7', TRUE),
    ('Healthcare',        'heart',         '#DDA0DD', TRUE),
    ('Shopping',          'shopping-bag',  '#F0E68C', TRUE),
    ('Income',            'trending-up',   '#98FB98', TRUE),
    ('Savings',           'piggy-bank',    '#87CEEB', TRUE),
    ('Other',             'more-horizontal','#D3D3D3', TRUE);

-- Transactions
CREATE TABLE transactions (
    id               BIGSERIAL PRIMARY KEY,
    account_id       BIGINT          NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    category_id      BIGINT          REFERENCES categories(id) ON DELETE SET NULL,
    amount           NUMERIC(19, 4)  NOT NULL,
    currency         VARCHAR(10)     NOT NULL DEFAULT 'USD',
    type             VARCHAR(20)     NOT NULL,  -- INCOME, EXPENSE, TRANSFER
    description      VARCHAR(500),
    merchant         VARCHAR(255),
    transaction_date DATE            NOT NULL,
    created_at       TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Budgets (envelope-style per category per month)
CREATE TABLE budgets (
    id            BIGSERIAL PRIMARY KEY,
    user_id       BIGINT         NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_id   BIGINT         NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    amount_limit  NUMERIC(19, 4) NOT NULL,
    month         DATE           NOT NULL,  -- stored as first day of the month
    created_at    TIMESTAMP      NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, category_id, month)
);

-- Recurring payments (e.g. subscriptions)
CREATE TABLE recurring_payments (
    id               BIGSERIAL PRIMARY KEY,
    user_id          BIGINT          NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    account_id       BIGINT          NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    category_id      BIGINT          REFERENCES categories(id) ON DELETE SET NULL,
    name             VARCHAR(255)    NOT NULL,
    amount           NUMERIC(19, 4)  NOT NULL,
    currency         VARCHAR(10)     NOT NULL DEFAULT 'USD',
    frequency        VARCHAR(50)     NOT NULL,  -- DAILY, WEEKLY, MONTHLY, YEARLY
    next_due_date    DATE            NOT NULL,
    active           BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMP       NOT NULL DEFAULT NOW()
);

-- Alerts generated by the anomaly/budget engine
CREATE TABLE alerts (
    id           BIGSERIAL PRIMARY KEY,
    user_id      BIGINT       NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    alert_type   VARCHAR(50)  NOT NULL,  -- BUDGET_BREACH, ANOMALY, RECURRING_DUE
    message      TEXT         NOT NULL,
    is_read      BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMP    NOT NULL DEFAULT NOW()
);

-- ============================================================
-- Indexes for query performance
-- ============================================================
CREATE INDEX idx_transactions_account_id   ON transactions(account_id);
CREATE INDEX idx_transactions_date         ON transactions(transaction_date);
CREATE INDEX idx_transactions_category     ON transactions(category_id);
CREATE INDEX idx_accounts_user_id          ON accounts(user_id);
CREATE INDEX idx_budgets_user_month        ON budgets(user_id, month);
CREATE INDEX idx_alerts_user_unread        ON alerts(user_id, is_read);
CREATE INDEX idx_refresh_tokens_user       ON refresh_tokens(user_id);
